name: Build Docker, and publish to Developer K8s
on:
  push:
    branches: [ master ]
jobs:
  jobName:
    name: Build Docker image and Push to AWS ECR
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: diogohudson/aws-ecr-vpn-eks-k8s-swissknife@master
      with:
         access_key_id: ${{ secrets.APP041_ACCESS_KEY_ID }}
         secret_access_key: ${{ secrets.APP041_SECRET_ACCESS_KEY }}
         account_id:  ${{ secrets.APP041_ACCOUNT_ID }}
         create_repo: true
         repo: azpartes-product-availability
         region: us-east-1
         tags: ${{ env.BRANCH }}
         cluster_name: k8-internal-testing
         kubectl_command: get pods
